FROM node:16-alpine AS builder

WORKDIR /app

COPY package.json ./

RUN npm install

COPY .   .

ENV PORT_VUE 3002


RUN npm run build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY  --from=builder /app/dist/ /usr/share/nginx/html


CMD ["nginx", "-g", "daemon off;"],               